"""initial schema

Revision ID: c2339ca93a90
Revises: 
Create Date: 2026-06-29 19:25:13.639075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2339ca93a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', 'teacher', 'tutor', name='userrole', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pwa_push_token', sa.String(length=512), nullable=True),
    sa.Column('pd_consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pd_consent_version', sa.String(length=40), nullable=False),
    sa.Column('consent_cohort_flag', sa.Boolean(), nullable=False),
    sa.Column('onboarding_session_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('grade IS NULL OR grade IN (8, 9, 10, 11)', name='ck_user_grade_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id')
    )
    op.create_table('daily_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('reviews_completed', sa.Integer(), nullable=False),
    sa.Column('morning_warmup_done', sa.Boolean(), nullable=False),
    sa.Column('missed_day_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_session_user_date')
    )
    op.create_index(op.f('ix_daily_sessions_user_id'), 'daily_sessions', ['user_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'passed', 'failed_today', name='progressstatus', native_enum=False), nullable=False),
    sa.Column('main_question_attempts', sa.Integer(), nullable=False),
    sa.Column('training_errors', sa.JSON(), nullable=False),
    sa.Column('current_message_id', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_on_attempt', sa.Integer(), nullable=True),
    sa.CheckConstraint('main_question_attempts >= 0 AND main_question_attempts <= 3', name='ck_progress_main_attempts'),
    sa.CheckConstraint('passed_on_attempt IS NULL OR passed_on_attempt IN (1, 2)', name='ck_progress_passed_on_attempt'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_user_lesson')
    )
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    op.create_table('reminder_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skip_days_count', sa.Integer(), nullable=False),
    sa.Column('freeze_applied_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Enum('passed_attempt_2', 'interval_1d', 'interval_3d', 'interval_7d', 'interval_14d', 'interval_30d', name='reviewreason', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_user_id'), 'review_queue', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('freeze_used_this_week', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('student_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('adult_user_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('parent', 'teacher', 'tutor', name='linktype', native_enum=False), nullable=False),
    sa.Column('link_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['adult_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_links_adult_user_id'), 'student_links', ['adult_user_id'], unique=False)
    op.create_index(op.f('ix_student_links_link_code'), 'student_links', ['link_code'], unique=False)
    op.create_index(op.f('ix_student_links_student_user_id'), 'student_links', ['student_user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_lesson_id', sa.String(length=40), nullable=False),
    sa.Column('course_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fsm_state', sa.String(length=64), nullable=False),
    sa.Column('enrollment_reason', sa.Enum('grade9_direct', 'grade10plus_retake', name='enrollmentreason', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_student_links_student_user_id'), table_name='student_links')
    op.drop_index(op.f('ix_student_links_link_code'), table_name='student_links')
    op.drop_index(op.f('ix_student_links_adult_user_id'), table_name='student_links')
    op.drop_table('student_links')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_review_queue_user_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_table('reminder_states')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_daily_sessions_user_id'), table_name='daily_sessions')
    op.drop_table('daily_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
